# Generated by Django 4.1.5 on 2023-02-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='edges', max_length=20)),
                ('lane_perspective_floor', models.PositiveIntegerField(default=250)),
                ('lane_perspective_roof', models.PositiveIntegerField(default=750)),
                ('lane_perspective_startfloor', models.PositiveIntegerField(default=250)),
                ('lane_perspective_stopfloor', models.PositiveIntegerField(default=750)),
                ('lane_perspective_startroof', models.PositiveIntegerField(default=250)),
                ('lane_perspective_stoproof', models.PositiveIntegerField(default=750)),
            ],
        ),
    ]
