# Generated by Django 4.1.4 on 2022-12-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgedetection',
            name='maxVal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='minVal',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
