# Generated by Django 4.1.4 on 2022-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_edgedetection_maxval_edgedetection_minval'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgedetection',
            name='name',
            field=models.CharField(default='edges', max_length=20),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='pos1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='pos2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='pos3',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
