# Generated by Django 4.1.5 on 2023-02-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_edgedetection_lane_perspective_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgedetection',
            name='lane_left_rect_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='lane_left_rect_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='lane_left_rect_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='lane_left_rect_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='lane_right_rect_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='lane_right_rect_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='lane_right_rect_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edgedetection',
            name='lane_right_rect_y',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
